Added feedback during server shutdown.

diff --git a/doc/doc b/doc/doc
--- a/doc/doc
+++ b/doc/doc
@@ -360,8 +360,12 @@ function maven() {
     # $3 = Temporary file
     # $4 = LogFile
 
+    # debug: Maven
+
     # debug: Stop the server
-    server_stop
+    server_stop $1 $2 $3 $4
+    Return=$?
+    if [ "$Return" != "0" ]; then return $Return; fi
 
     # debug: Compile jars
     pushd ../ > /dev/null
@@ -377,12 +381,6 @@ function maven() {
     popd > /dev/null
     if [ "$Return" != "0" ]; then return $Return; fi
 
-    # debug: Update the additional python documentation files
-#   pushd ../python > /dev/null
-#   build_docstubs $1 $2 $3 $4
-#   Return=$?
-#   popd > /dev/null
-
     return $Return
 
 }
@@ -392,7 +390,8 @@ function packages() {
     # $1 = User id name
     # $2 = ScriptPath
 
-    # Give the filename of the list of people with ability to load python packages
+    # debug: Give the filename of the list of people with ability to
+    # debug: load python packages
     TECHWRITERS=techwriters
     # Yes for "packages", check for permissions
     if [ -f $2/$TECHWRITERS ]; then
@@ -426,7 +425,7 @@ function pdf_build() {
     # $5 = Temporary file
     # $6 = LogFile
 
-    # Build a pdf from another source, currently limited to latex
+    # debug: Build a pdf from another source, currently limited to latex
 
     BuildDirectory="build/$1"
     Extension="tex"
@@ -463,7 +462,12 @@ function server_start() {
     # $3 = Temporary file
     # $4 = LogFile
 
-    # Start the server
+    # debug: First, kill any existing server running
+    server_stop $1 $2 $3 $4
+    Return=$?
+    if [ "$Return" != "0" ]; then return $Return; fi
+
+    # debug: Start the server
     echo -n "nohup bin/api-server.sh"
     log_step "nohup bin/api-server.sh" "No" $4
     nohup bin/api-server.sh < /dev/null > $3 2>&1 &
@@ -486,14 +490,41 @@ function server_start() {
 
 ############################################################################################################
 function server_stop() {
+    # $1 = AskThem
+    # $2 = DisplayStatus
+    # $3 = Temporary file
+    # $4 = LogFile
 
-    # Stop the server
-    pid=$(ps aux 2>&1  | grep "java.*launcher/target/launcher.jar.*com.intel.intelanalytics.component.Boot" | head -n 1 |  awk '{print $2}')
-    ps|grep $pid > /dev/null
-    if [ "$?" == "0" ]; then
-        kill $pid 2>&1 > /dev/null
-    fi
-    return
+    # debug: Stop the server
+    let "LoopCounter = 24"
+    until [[ $LoopCounter -le 0 ]]; do
+        pid=$(ps aux 2>&1  | grep "java.*launcher/target/launcher.jar.*com.intel.intelanalytics.component.Boot" | head -n 1 |  awk '{print $2}')
+        ps|grep $pid > /dev/null
+        if [ "$?" == "0" ]; then
+            echo -n "Stop server $pid"
+            kill $pid
+            if [ $? != 0 ]; then
+                echo
+                Err "Stop server $pid" $1 $2 $3 $4
+                Return=$?
+                if [[ "$Return" != "0" ]]; then
+                    return $Return
+                fi
+            fi
+            let "DURATION = 2"
+            until [[ $DURATION -le 0 ]]; do
+                sleep 1
+                echo -n "."
+                let "DURATION -= 1"
+            done
+            echo
+            let "LoopCounter -= 1"
+        else
+            return 0;
+        fi
+    done
+    Err "Unable to stop server."
+    return $?
 }
 
 ############################################################################################################
@@ -504,6 +535,8 @@ function sphinx_build() {
     # $4 = Temporary file
     # $5 = LogFile
     # $6 = Modified Arguments
+
+    # debug: sphinx_build()
 
     BuildDirectory="build/$1"
 
@@ -519,4 +552,3 @@ function sphinx_build() {
 
 #==========================================================================================================#
 main $(parameters "$*")
-server_stop
